### PR TITLE
Allow `.transform()` to take DOMMatrix or CSS `transform` strings as arguments

### PR DESCRIPTION
**Pull request by mpaperno**
* Context's `transform()` method can now accept a `DOMMatrix` (or matrix-like object), or array, as a single argument;
  * `Path2D.transform()` can also now accept a list or array of values instead of `DOMMatrix`, though I'm sure why anyone would need that.
* Make transform matrix arguments for all relevant methods more flexible to accept any matrix-like object (not just `DOMMatrix` instance) or an array;
* Throw an exception if matrix argument(s) cannot be parsed (instead of trying to use an invalid matrix, which conforms to browser behavior);
* Fixed possible exception in `DOMMatrix.fromMatrix()` and `DOMPoint.matrixTransform()` due to missing `SVGMatrix` type definition;
* Fixed that `DOMMatrix.fromMatrix()` only worked on DOMMatrix instances instead of any matrix-like object;
* Added `DOMMatrix` static functions `isMatrix3()` and `isMatrix4()` and prototype method `clone()`;
* `DOMMatrix` c'tor can now accept another matrix-like object directly (like `fromMatrix()`), or a simple list of 6/16 values;
* Adjusted TS definitions for relevant methods;
* Added transform() tests;
* Added docs for new `Context2D.transform()` variant.

It was simpler to just add in the new `transform()` feature here than trying to split it up, since the fixes touched the same code... hope you don't mind.

This adds the same [`drawPinwheel()`](https://github.com/samizdatco/skia-canvas/pull/174/files#diff-1711e9363a67d25dad2c23f38c44d815d4b29bce6d5ddc10a70d2c1564bcc09cR266) function in visual tests as #174, but hopefully it won't conflict since it should be exactly the same function. I'll fix it up if any conflicts.

EDIT: I tried a local merge of everything so far, in order of submission, and this one does conflict on one line in the visual tests (argh).  So I'll convert this to draft for now and fix it up once the others are in.

Related to: #172

### CODE REVIEW

**Comment by samizdatco** [comment]
Now that the shadow fix is merged you should be able to clear up the conflict here with a `git rebase maintenance-2024`

**Comment by mpaperno** [comment]
All set.

**Comment by samizdatco** [comment]
After trying to fix the typescript definitions for DOMMatrix in a half-dozen ways I went with the brute-force approach and just copied the whole definition into the d.ts file. As a result there are no longer compiler warnings about the return values of methods like `.scale` returning a version of DOMMatrix that lacks the `clone` (and now also `skew` and `skewSelf`) methods in the subclass. I also simplified the signatures for the transform-related methods that can now accept more than one style of matrix specification.

One additional feature I added (which has some tests but could use some real-world evaluation) is the ability to use CSS-style [`transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function) strings in all the places that you'd otherwise pass in a DOMMatrix or 6-number combination. It's a small thing, but the css syntax is nicely concise and allows for unit conversions that could otherwise be a bit of a pain:

```js
ctx.setTransform(new DOMMatrix().scale(2, 0.5).translate(10, 10)) // matrix-style
ctx.setTransform(new DOMMatrix().rotate(.333/Math.PI * 180))

ctx.setTransform('scale(2, 50%) translate(10, 10)') // css-style
ctx.setTransform('rotate(.333rad)')
```

The new `skew` & `skewSelf` matrix methods are there to allow for the combined x & y skew operation that the CSS interface exposes, but seemed useful enough to add to the object.

**Comment by mpaperno** [comment]
Yea wow you took this pretty seriously...  :)  Looks good!

Guess I need to get a TS compiler involved in the testing on some sample project...  I've mostly just been checking editor hinting/error reporting, TBH.  Got a love/hate thing with TS... 😅 

The CSS style parser is a nice feature too. I'm not sure my sense of efficiency would allow me to use strings where good old numbers will work, but I get the attraction! Especially for users of a drawing app... like the one I work on, might be handy.

**Pull request merged**
